### ISSUE TITLE
Failed to open /sys/class/net/bonding_masters/statistics/rx_bytes: Not a directory

### ISSUE THREAD

**Issue by astalush** [stolk/ifgraph#5]
I have this error:
Failed to open /sys/class/net/bonding_masters/statistics/rx_bytes: Not a directory

I have a bond0 created which works well but I cannot use your tool to see the traffic on this bond0

When I start the ifgraphd service it doesn't see the bond0, only bonding_masters

But the /sys/class/net/bond0/statistics/rx_bytes exists

thanks.

**Comment by stolk** [comment]
Thank you for reporting.

I assume both `bond0` and `bonding_masters` are in `/sys/class/net/` directory? If so, I should filter out the masters entry I think.

**Comment by astalush** [comment]
Yes they are. Bond0 is a directory where bonding_masters is a file that contains one line , line that is “bond0” :-)

**Comment by stolk** [comment]
> Yes they are. Bond0 is a directory where bonding_masters is a file that contains one line , line that is “bond0” :-)

Should be fixed now. Can you try latest? Note: with the daemon running, you can start the client, and limit the stuff that is shown, so only show the bond0 e.g.

**Comment by astalush** [comment]
Tested. Cannot see the bond0 traffic.

Recording statistics for veth7e802be veth2e41882 veth0db6313 veth06cce13 docker0 veth017eeb4 veth35d628e vethd594031 enp5s0 veth103c8ff vethf3e6efd veth8c7feda veth2a04258 veth9d1d0ba vethae
c2c99 veth13f214c veth5c5242d vetha5ca8ee vethe5566c2 vethf076bda enp3s0f3 veth160e565 enp3s0f1 vethcb78b63 veth881027b vethc6ebfc3 vethbbf0437 veth4c680e0 vethbda26ee vethf8d0269 vethe632ab
5 vethf9e1744 but no bond0
